(ql:quickload :cl-bunny.examples)

(in-package :cl-bunny.examples)

(with-connection ("amqp://")
  (with-channel ()
    (let ((n 1)
          (x (amqp-exchange-declare "logs" :type "fanout"))
          (q (queue.declare "" :auto-delete t)))
      (amqp-queue-bind q :exchange x)
      (format t " [*] Waiting for logs. To exit type (exit)~%")
      (subscribe q (lambda (message)
                     (let ((body (babel:octets-to-string (message-body message))))
                       (format t " [x] #~a~%" body)))
                 :type :sync)
      (consume))))
